"""users delete fk

Revision ID: 29e44ccd2abe
Revises: 42e8e7961ed8
Create Date: 2024-06-04 19:36:39.436362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e44ccd2abe'
down_revision: Union[str, None] = '42e8e7961ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_role_fkey', 'users', 'roles', ['role'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
